/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
// import { ThemeProvider } from "next-themes";
import Providers from "@/shared/lib/providers";

const poppin = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Base Project App",
  description: "Generated by Base Project app",
};

const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || '';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={poppin.variable}>
        <GoogleOAuthProvider clientId={clientId}>
          <Providers>
            {/* <ThemeProvider attribute="class" defaultTheme="dark"> */}
              {children}
            {/* </ThemeProvider> */}
          </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
